import Tree
t1 = Tree.Tree()

t1.insere(4)
t1.insere(2)
t1.insere(1)
t1.insere(3)
t1.insere(6)
t1.insere(5)
t1.insere(7)
t1.insere(8)
t1.insere(9)
t1.insere(10)
t1.insere(11)

print('IN-ORDEM:')
t1.inOrdem()
print('\n*****')
print('\nPRE-ORDEM:')
t1.preOrdem()
print('\n*****')
print('\nPOS-ORDEM:')
t1.posOrdem()
print('\n*****')
print('\nConta Quantidade:')
print(t1.contaQtd(5))
print('\n*****')
print('\nMaior que:')
t1.maiorQue(5)
print('\n*****')
print('\nSoma')
print(t1.soma())
print(t1.somaMaiores(4))
