import Ldde
l = Ldde.Ldde()

print('1')
l.inserirInicio('A')
l.inserirFim('B')
l.inserirFim('C')
l.inserirFim('D')
l.removerInicio()
l.show()
print('*****')
l.inserirInicio('A')
l.showReverso()
print('******')
l.show()
print('*****')
print('2')
l.inserirApos('A','B1')
l.show()
print('*****')
print('3')
l.inserirApos('B','C1')
l.show()
print('*****')
print('4')
l.inserirApos('D','E')
l.show()
print('*****')
print('5')
l.inserirApos('E','F')
l.show()
print('*****')
print('6')
l.inserirApos('D','E1')
l.show()
print('*****')
print('7')
l.inserirApos('C','D1')
l.showReverso()


